spring:
  application:
    name: yousinsa

  # .env import
  config:
    import: optional:file:.env[.properties]

  # DB
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행

  sql:
    init:
      mode: always

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
